baseURL = "https://kociol.vcc.earth/"
languageCode = "en-us"
title = "Kolektyw KOCIOŁ"
defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  orgName = "Kolektyw KOCIOŁ"
  description = "Strona naszej organizacji"

[taxonomies]
  tag = "tags"
  category = "categories"
