backend:
  name: github
  repo: cr1tbit/kociol-online
  branch: main
  base_url: https://priv.vcc.earth
  auth_endpoint: auth

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

site_url: https://kociol.vcc.earth
display_url: https://kociol.vcc.earth

collections:
  - name: pages
    label: Pages
    files:
      - name: kociol_info_index
        label: Kocioł info (index)
        file: content/kociol-info/_index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
            required: false
      - name: kalendarz
        label: Kalendarz
        file: content/kalendarz.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish date
            name: date
            widget: datetime
            required: false
          - label: Draft
            name: draft
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - name: album_zdjec
        label: Album zdjęć
        file: content/album-zdjec.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish date
            name: date
            widget: datetime
            required: false
          - label: Draft
            name: draft
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - name: kotlownia
        label: Kotłownia
        file: content/kotlownia.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish date
            name: date
            widget: datetime
            required: false
          - label: Draft
            name: draft
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - name: discord
        label: Discord
        file: content/discord.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish date
            name: date
            widget: datetime
            required: false
          - label: Draft
            name: draft
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
  - name: kociol_info
    label: Kocioł info subpages
    folder: content/kociol-info
    create: true
    slug: "{{slug}}"
    preview_path: kociol-info/{{slug}}/
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish date
        name: date
        widget: datetime
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Summary
        name: summary
        widget: text
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    preview_path: posts/{{slug}}/
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish date
        name: date
        widget: datetime
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Summary
        name: summary
        widget: text
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
  - name: site_data
    label: Site Data
    files:
      - name: calendar_months
        label: Kalendarz Miesięcy
        file: data/calendar/months.yaml
        fields:
          - label: Months
            name: months
            widget: list
            summary: "{{fields.month}} {{fields.year}}"
            fields:
              - label: Month
                name: month
                widget: string
              - label: Year
                name: year
                widget: number
                value_type: int
                min: 2000
              - label: Image
                name: image
                widget: image
